labels:
  claim_probability: 0.20
  claim_severity:
    distribution: gamma
    shape: 2.0
    scale: 500.0
  random_seed: 42
  use_feature_weights: true
  feature_weights:
    harsh_brake_rate: 1.5
    harsh_accel_rate: 1.3
    night_trip_ratio: 1.2

schema: "docs/schemas/training_labels_v1.avsc"
