seed: 123
num_drivers: 5
events_per_second: 1

trip:
  min_minutes: 2
  max_minutes: 2
  avg_speed_mps: 12.5
  speed_stddev: 2.0
  harsh_brake_prob: 0.01
  harsh_accel_prob: 0.01

geofence:
  lat_min: 37.70
  lat_max: 37.80
  lon_min: -122.50
  lon_max: -122.40

output:
  format: ["parquet", "avro"]
  path: "/content/Sreekumar_Ajay_TelematicsUBI/data/sample/telematics_sample"
